spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apidb
    username: apidbuser
    password: apidbuser

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  #  업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

org:
  zerock:
    upload:
      path: upload

logging:
  level:
    org:
      springframework:
        security:
          web: trace